server:
   port: 8081
   #servlet:
      #session:
         #timeout: 60
 
#C:\Documents and Settings\All Users\MySQL\MySQL Server 5.7\Data
spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smartinstall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 1332080218
      #password: Lo7!1pJI8#Ko*$t
      separator: $$
      initialization-mode: ALWAYS
      schema:
         - classpath:sql/sql_*.sql
   jackson:
      serialization:
         indent-output: true
   thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      servlet:
         content-type: text/html
      mode: HTML
      cache: false
   session:
      store-type: redis
   redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
         pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
      timeout: 5000
   data:
      mongodb:
         uri: mongodb://localhost:27017/test
   mail:
      host: smtp.163.com
      username: xum1281517532@163.com
      password: 1332080218
      default-encoding: UTF-8
      protocol: smtp

#mybatis 
mybatis:
   mapper-locations: classpath:mapper/*.xml
   config-location: classpath:config/mybatis/mybatis_config.xml
   type-aliases-package: com.xum.cmnd.pojo

#cas:
#   validation-type: CAS
#   server-url-prefix: http://192.168.80.96:8084/cas
#   server-login-url: http://192.168.80.96:8084/cas/login
#   client-host-url: http://localhost:8080
#actuator
# http://localhost:9091/actuator
management:
   server:
      port = 9091
   endpoint:
      health:
         show-details: always
      web:
         exposure:
            include: '*'
